version: "3.8"

services:
  storage-service-api:
    build:
      context: ./service
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_USER: ${STORAGE_SERVICE_API_DATABASE_USERNAME}
      DATABASE_PASSWORD: ${STORAGE_SERVICE_API_DATABASE_PASSWORD}
      DATABASE_DOMAIN: ${STORAGE_SERVICE_DATABASE_DOMAIN}
      DATABASE_NAME: ${STORAGE_SERVICE_DEV_DATABASE}
    volumes:
      - ./service:/go/src
      - .pkg:/go/pkg

  storage-service-db:
    build:
      context: ./service/infrastructure/database
      dockerfile: Dockerfile.dev
    environment:
      POSTGRES_USER: ${ADMIN_USER}
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
      POSTGRES_DB: ${STORAGE_SERVICE_ADMIN_DATABASE}
    volumes:
    - storage-service-data:/var/lib/postgresql/data

  migrations:
    build:
      context: ./service/infrastructure/migrations
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URI: ${STORAGE_SERVICE_MIGRATIONS_DATABASE}
    volumes:
    - ./service/infrastructure/migrations:/go/src

  management-tool:
    build:
      context: ./management-tool
      dockerfile: Dockerfile
    environment:
      STORAGE_SERVICE_DATABASE_DOMAIN: ${STORAGE_SERVICE_DATABASE_DOMAIN}
      STORAGE_SERVICE_DATABASE_USER: ${ADMIN_USER}
      STORAGE_SERVICE_DATABASE_PASSWORD: ${ADMIN_PASSWORD}
      STORAGE_SERVICE_ADMIN_DATABASE: ${STORAGE_SERVICE_ADMIN_DATABASE}

volumes:
  storage-service-data:
